### ISSUE TITLE
List of Videos

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#1]
## Value Statement

As a **novice orator**
I can **watch a fixed set of short speeches/videos**
so that I can get a **first feeling for good rhetoric**.

## Description (Text, Scribble, Wireframe, Design)

- A list of cards. Each card contains a video and information about the video: title, description, speaker, duration, date.

[Scribble](https://drive.google.com/file/d/1oKgX7J5czf2JAzIyRWza5Gfgt3FKMzpZ/view?usp=sharing)

## Acceptance Criteria

- [x] Cards have to be visually separated.
- [x] Videos play when clicked.

## Tasks

- [x] Download ~5 appropriate short speeches and store locally.
- [x] Setup a JSON server that stores information about the videos, including their local path
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view

## Size

Medium
