### ISSUE TITLE
Add firebase authentification

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#10]
## Register and Sign in with Firebase

As a **user**
I can **register and sign in on the entry page to the app via firebase**
in order to **upload my own speeches and my own evaluations**.

## Description (Text, Scribble, Wireframe, Design)

- When loading the app, the app checks if the user still signed in and forwards him directly to the next page if signed in.
- If the user is not signed in, the first page shows a sign in form.
- The user can either sign in with his e-mail address and his password or create a new user account.

## Acceptance Criteria

- [x] Opening the app checks if the user is still signed in via a comparison with the local storage.
- [x] If the user is not signed in, the first page shows a sign form asking for the e-mail address and a password.  
- [x] Beneath the sign in form, a button offers new users to "Sign Up".
- [x] After clicking the "Sign Up" button, a registration form opens, containing the email address, password, first and last name.

## Tasks

- [x] Add a logic (probably by Firebase) checking if the user is still signed in via a comparison with the local storage. 
- [x] If the user is not signed in, show the form to sign in plus a "Sign Up" button.
- [x] Add the "Sign Up" button.
- [x] Implement Firebase and its signing in and registration logic.
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view

## Size

Large
