### ISSUE TITLE
Add Firestore as database

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#11]
## Register and Sign in with Firebase

As a **user**
I can **now use the app from anywhere**
**provided I have the browser and the app's url**.

## Description (Text, Scribble, Wireframe, Design)

- The app's database is moved from JSON server to Google Firestore.
- The app is deployed via Google Hosting.

## Acceptance Criteria

- [x] All the database operations that are required for the moment work via moved to firestore.
- [x] The app can be reached and used via a internet browser from anywhere and any device.

## Tasks

- [x] Setup Google Firestore. 
- [x] Import the Firestore Database.
- [x] Adapt all speechServices to Firestore.
- [x] Host and deploy the app via Google Hosting.
- [x] Test in mobile and desktop view

## Size

Large
