### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#16]
## Value Statement

As a **(novice/skilled) orator**
I can **log out by clicking on the profile icon** inside the right bottom corner
so that **I have a larger view upon the communities content**.

Furthermore, the app receives a redesign improving the user experience on mobile and desktop.

## Description (Text, Scribble, Wireframe, Design)

- Adding icons in place of the footer.
- The profile icon in the right bottom corner opens an navigation bar containing of yet just another icon that allows to log out.
- The icon in the left bottom corner reminds one of recording a video. Clicking this button will just show a message, announcing the possibility to upload speeches soon.
- Reducing overall font size.
- Create bars instead of circles for the evaluation dimensions.
- Redesign of the color scheme.

## Acceptance Criteria

- [x] Profile icon in the right bottom corner toggles a navigation bar on click.
- [x] The navigation bar shows another icon allowing the user to log out on click.
- [x] The icon in the left bottom corner shows a message on click.

## Tasks

- [x] Create and implement the necessary icons.
- [x] Add the toggle logic to open the nav bar.
- [x] Add the log out logic.
- [x] Add the logic to show a message when clicking on the "cinematic" icon.
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view

## Size

small
