### ISSUE TITLE
Evaluate Videos

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#2]
## Value Statement

As a **novice orator**
I can **evaluate a fixed set of short speeches/videos**
so that I **understand what skills and techniques are important for a good speech**.

## Description (Text, Scribble, Wireframe, Design)

- A list of cards with videos. 
- Clicking a card opens the video on another page. Underneath the video description a short questionnaire opens. Here the user can evaluate the quality of the speech.
- First, he can enter his name to associate the evaluation to himself.
- Next, there are several 5 step range inputs: gestures and facial expressions, pronounciation and vocal variety, comprehensibility and structure, stylistic devices, credible and convincing
[Scribble](https://drive.google.com/file/d/16KhClCV1aK9abo4hGN9p4cO8HcpKEQ-r/view?usp=sharing)

## Acceptance Criteria

- [x] Click on a card opens a new page with the video, video description and evaluation form.
- [x] The evaluation form contains a mandatory input field for the evaluator's name and a set of 5-step range inputs.
- [x] After submitting the user gets a confirmation message and the form is resetted.
- [x] The evaluation shall be stored in a JSON file alongside the other information related to the specific video. 

## Tasks

- [x] Create a new page that opens when clicking a video.
- [x] A return button allows to return to the video list.
- [x] The new page contains the video, video description and the specified evaluation form.
- [x] Submitting saves the data in the JSON file alongside the other video data, returns a confirmation message and resets the form.
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view
- [ ] Write unit and ui tests

## Size

Medium
