### ISSUE TITLE
Issue 9 Profile Page

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#21]
## Value Statement

As a **novice orator**
I can **edit my profile page**
so that I **can tell something about myself, change my password and upload a portrait**.

## Description (Text, Scribble, Wireframe, Design)

- The user can open his profile page via the nav bar in the bottom right corner.
- There he can change his password, write a short bio describing why joined Ciceroic, and upload a portrait.

[Scribble](https://drive.google.com/open?id=1kelOcVPxjffXCRSqdus0l7xtxE0mPtsm)

## Acceptance Criteria

- [x] The profile page can be accessed via the profile icon in the bottom right corner.
- [ ] The profile page shows an overview of the user information: name, email address, portrait, bio and uploaded speeches.
- [x]  Clicking on the portrait opens the image in a bigger screen and shows two buttons saying "Delete" and "Upload".
- [x] Clicking the "Delete" button shows a text asking if the user really wants to delete the image and two more buttons to confirm or decline the operation. 
- [x] An edit button underneath the profile page allows to edit the bio when clicking.
- [x] A button next to the email address allows to change the password. Clicking on the button shows three inputs, the first one for the current password, the two last ones to input the new password repeatedly. If the password is correct, the password will be reset and sent to the db. If the current password is wrong or the new password does not fulfill the criteria, a message informs the user about the issue.

## Tasks

- [x] Create a profile page.
- [x] Fetch data from DB.
- [x] Add a text input and image input.
- [x] Fill the protrait by a default image if the user hasn't uploaded one.
- [x] Add the upload logic to save a portrait in the firebase storage and link it to the user.
- [x] Add the upload logic to allow the user to submit and change his bio.
- [x] Add the logic to reset the user's password.
- [x] Create necessary components
- [x] Styling
- [ ] Test in mobile and desktop view

## Size

Large
