### ISSUE TITLE
See Video Evaluations

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#3]
## Value Statement

As a **novice orator**
I can **see user evaluations for a fixed set of short speeches/videos**
so that I **understand how good speakers use rhetoric skills and techniques**.

## Description (Text, Scribble, Wireframe, Design)

- The evaluation form on a video details page contains two tabs: [evaluate speech] [average evaluation]
- By default, the first tab is opened showing the possible inputs.
- Clicking the second tab opens the average values from the previous evaluations.
- If no evaluations have been given yet, a message is shown saying: 'This speech received no evaluations yet. Be the first and give the speaker a review.' – and linking back to the first tab.
- Optional: connect statistics (points indicating average values) with a line

[Scribble](https://drive.google.com/file/d/1IYjFznUZ8IfBsfav1hOqQgSE53NUKUXn/view?usp=sharing)

## Acceptance Criteria

- [x] The evaluation area starts with two tabs.
- [x] The first tab is opened by default and shows the evaluation form as before.
- [x] The second tab opens the average values from the previous evaluations.
- [x] If no evaluations have been given, the tab shows the specified message with a link back to the evaluation form.
- [ ] optional: A line connects the points indicating the average evaluations per category.
- [ ] optional: The line is responsive and adapts to a window resize.

## Tasks

- [x] Create two tabs link to two separate components, while the first component is opened by default.
- [x] Calculate the average values from previous evaluations contained in the JSON file and show these in the second tab.
- [x] Implement the logic if no evaluations have been given.
- [x] The new page contains the video, video description and the specified evaluation form.
- [x] Create necessary components
- [x] Styling
- [ ] Test in mobile and desktop view
- [ ] optional: Draw a svg line connecting the points indicating the average evaluations.
- [ ] optional: The svg line's values reference the nodes in every aspect, thus being responsive to window resize.

## Size

Small
