### ISSUE TITLE
Write speech evaluations

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#4]
## Value Statement

As a **(novice/skilled) orator**
I can **write and read evaluations to a fixed set of short speeches/videos**
in order to **understand or to show how good speakers use rhetoric skills and techniques**.

## Description (Text, Scribble, Wireframe, Design)

- The evaluation form inside the first tab of a individual speech is extended by two text inputs: [What I liked about the speech.] [What could be improved.]
- The second tab shows (underneath the average evaluation values) the total number of given evaluations.
- All evaluations consist of three parts according to the inputs (range values, praise and suggestions). 
- [Scribble](https://drive.google.com/open?id=1Shjmw1zbp1CbOdMO3iik4MNoiRa9Y9IE)

## Acceptance Criteria

- [x] The evaluation input form is extended by two text areas.
- [x] The data is stored inside the db.
- [x] The evaluation can be edited after submitting.

## Tasks

- [x] Extend the input form and save the additional data in the speech object in the databse.
- [x] Add an edit button and editing logic.
- [x] Retrieve the evaluations from the database and display these inside that tab "Feedback".
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view

## Size

Medium
