### ISSUE TITLE
Vote and Flag Evaluations

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/capstone-project#5]
## Value Statement

As a **(novice/skilled) orator**
I can **up- and downvote evaluations or flag evaluations as inappropriate**
so that **high-quality evaluations are ranked at the top and inappropriate evaluations are automatically deactivated**.

## Description (Text, Scribble, Wireframe, Design)

- The evaluations in the second tab of the video details page can be up- and downvoted and marked as unappropriate.

## Acceptance Criteria

- [x] Displayed evaluations get a footer with three icons for up-, downvote and flag.
- [x] Next to the up- and downvote icon is a counter showing the sum of the previous votes.
- [x] The user can only vote or flag an evaluation once.
- [x] The user can change his up- or downvote anytime.
- [x] The votes and flag are saved in the speech object in the db.
- [x] The buttons are marked if the user has once submitted a vote.

## Tasks

- [x] Extend the evaluations with a footer containing 3 clickable icons.
- [x] Up- and downvotes are added to / subtracted from the total value of votes by 1.
- [x] Save the additional data in the speech object in the db after each click.
- [x] Check every time the user clicks an icon if he/she has clicked it before. Up- and downvote buttons behave like toggle buttons allowing to correct a vote at any time.
- [x] Clicking the downvote icon after clicking the upvote button takes away the previous upvote and vice versa.  
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view

## Size

Medium
